karma:
  build: .
  command: java -jar server/target/server-0.0.1-jar-with-dependencies.jar
  ports:
    - "8081:8081"
  volumes:
    - ./:/app/karma
  links:
    - db_karma:db_karma
  tty: true


db_karma:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: karma
    MYSQL_DATABASE: karma
    MYSQL_USER: karma
    MYSQL_PASSWORD: karma
  ports:
    - "3307:3306"
  volumes:
    - ./:/app/